Update dotnet-desktop.yml

diff --git a/.github/workflows/dotnet-desktop.yml b/.github/workflows/dotnet-desktop.yml
--- a/.github/workflows/dotnet-desktop.yml
+++ b/.github/workflows/dotnet-desktop.yml
@@ -84,17 +84,15 @@ jobs:
 
     # Execute all unit tests in the solution
     - name: Execute unit tests
-      run: dotnet test $env:Test_Project_Path --logger "trx;LogFileName=$env:Test_Dir/testResults.trx"
+      run: dotnet test $env:Test_Project_Path --logger "trx;LogFileName=testResults.trx --results-directory "$env:Test_Dir/TestResults""
 
-    - name: Convert TRX to JUnit XML
-      run: |
-        dotnet tool install --global trx2junit
-        trx2junit $env:Test_Dir/testResults.trx $env:Test_Dir/testResults.xml
+    - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: NUnit Tests            # Name of the check run which will be created
+          path: $env:Test_Dir/TestResults/test-results.trx    # Path to test results
+          reporter: dotnet-trx        # Format of test results
         
-    - name: Upload Test Results
-      uses: actions/upload-artifact@v2
-      with:
-        name: Test Results
-        path: $env:Test_Dir/testResults.xml
 
   
